site_name: PL/SQL & SQL Coding Guidelines
site_url: https://trivadis.github.io/plsql-and-sql-coding-guidelines/

repo_name: trivadis/plsql-and-sql-coding-guidelines
repo_url: https://github.com/trivadis/plsql-and-sql-coding-guidelines
edit_uri: ""

theme:
  logo: images/trivadis-logo.svg
  icon:
    repo: fontawesome/brands/github-alt
  name: 'material'
  features:
    - navigation.instant
  favicon: images/favicon.ico
  palette:
    primary: 'white'
    accent: 'red'

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
      linenums_style: table
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra:
  guideline_version: 4.4
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Trivadis
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/trivadis
  version:
    provider: mike

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: false
